// 第3合集-AI时代编程新范式：Vibe Coding/260306-大模型编程能力实测/02-模型源码/Step-3.5-Flash/bilibili-clone/frontend/src/components/video/VideoCard.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { VideoInfo } from '../../types';
import { Card } from '../common';

interface VideoCardProps {
  video: VideoInfo;
  size?: 'normal' | 'small';
}

export const VideoCard: React.FC<VideoCardProps> = ({ video, size = 'normal' }) => {
  const formatNumber = (num: number): string => {
    if (num >= 100000) {
      return (num / 10000).toFixed(1) + '万';
    } else if (num >= 10000) {
      return (num / 10000).toFixed(1) + '万';
    } else if (num >= 1000) {
      return (num / 1000).toFixed(1) + '千';
    }
    return num.toString();
  };

  const formatDuration = (seconds: number): string => {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = seconds % 60;

    if (h > 0) {
      return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
    }
    return `${m}:${s.toString().padStart(2, '0')}`;
  };

  const coverUrl = video.cover || 'https://via.placeholder.com/320x200?text=No+Cover';

  if (size === 'small') {
    return (
      <Card hoverable className="group">
        <Link to={`/video/${video.bvid}`}>
          <div className="relative">
            <img
              src={coverUrl}
              alt={video.title}
              className="w-full object-cover aspect-video"
            />
            <span className="absolute bottom-1 right-1 bg-black bg-opacity-70 text-white text-xs px-1 rounded">
              {formatDuration(video.duration)}
            </span>
          </div>
          <div className="p-2">
            <h3 className="text-sm font-medium text-bili-text line-clamp-2 group-hover:text-bili-pink transition-colors">
              {video.title}
            </h3>
            <div className="mt-1 flex items-center gap-2 text-xs text-bili-text-gray">
              <span>{formatNumber(video.stat.view)}播放</span>
              <span>{formatNumber(video.stat.danmaku)}弹幕</span>
            </div>
          </div>
        </Link>
      </Card>
    );
  }

  return (
    <Card hoverable className="group">
      <Link to={`/video/${video.bvid}`}>
        <div className="relative">
          <img
            src={coverUrl}
            alt={video.title}
            className="w-full object-cover aspect-video"
          />
          <span className="absolute bottom-1 right-1 bg-black bg-opacity-70 text-white text-xs px-1 rounded">
            {formatDuration(video.duration)}
          </span>
          {video.videos > 1 && (
            <span className="absolute top-1 left-1 bg-bili-pink text-white text-xs px-1.5 py-0.5 rounded">
              合集
            </span>
          )}
        </div>
        <div className="p-3">
          <h3 className="font-medium text-bili-text line-clamp-2 group-hover:text-bili-pink transition-colors">
            {video.title}
          </h3>
          <div className="mt-2 flex items-center gap-2">
            <img
              src={video.owner.face || '/default-avatar.png'}
              alt={video.owner.name}
              className="w-5 h-5 rounded-full object-cover"
            />
            <span className="text-sm text-bili-text-gray truncate">{video.owner.name}</span>
          </div>
          <div className="mt-2 flex items-center gap-3 text-xs text-bili-text-gray">
            <span>{formatNumber(video.stat.view)}播放</span>
            <span>{formatNumber(video.stat.danmaku)}弹幕</span>
            <span>{formatNumber(video.stat.reply)}评论</span>
          </div>
        </div>
      </Link>
    </Card>
  );
};

// 第3合集-AI时代编程新范式：Vibe Coding/260306-大模型编程能力实测/02-模型源码/GLM-5/frontend/src/components/VideoCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'

interface Props {
  video: {
    bvid: string
    aid: number
    title: string
    cover: string
    duration: number
    play: number
    danmaku: number
    author?: string
    description?: string
  }
}

const props = defineProps<Props>()
const router = useRouter()

// 格式化时长
const formatDuration = (seconds: number) => {
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = seconds % 60
  if (h > 0) {
    return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`
  }
  return `${m}:${s.toString().padStart(2, '0')}`
}

// 格式化数字
const formatCount = (num: number) => {
  if (num >= 10000) {
    return (num / 10000).toFixed(1) + '万'
  }
  return num.toString()
}

// 点击跳转
const handleClick = () => {
  router.push({ name: 'Video', params: { bvid: props.video.bvid } })
}
</script>

<template>
  <div class="video-card" @click="handleClick">
    <div class="cover">
      <img :src="video.cover" :alt="video.title" loading="lazy" />
      <span class="duration">{{ formatDuration(video.duration) }}</span>
    </div>
    <div class="info">
      <h3 class="title" :title="video.title">{{ video.title }}</h3>
      <div class="meta">
        <span v-if="video.author" class="author">
          <svg viewBox="0 0 24 24" width="14" height="14" fill="currentColor">
            <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z" />
          </svg>
          {{ video.author }}
        </span>
        <span class="play">
          <svg viewBox="0 0 24 24" width="14" height="14" fill="currentColor">
            <path d="M8 5v14l11-7z" />
          </svg>
          {{ formatCount(video.play) }}
        </span>
        <span class="danmaku">
          <svg viewBox="0 0 24 24" width="14" height="14" fill="currentColor">
            <path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H6l-2 2V4h16v12z" />
          </svg>
          {{ formatCount(video.danmaku) }}
        </span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.video-card {
  background-color: var(--bg-primary);
  border-radius: var(--border-radius);
  overflow: hidden;
  cursor: pointer;
  transition: all var(--transition-normal);
}

.video-card:hover {
  transform: translateY(-4px);
  box-shadow: var(--shadow-md);
}

.cover {
  position: relative;
  width: 100%;
  aspect-ratio: 16 / 9;
  overflow: hidden;
  background-color: var(--bg-tertiary);
}

.cover img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform var(--transition-normal);
}

.video-card:hover .cover img {
  transform: scale(1.05);
}

.duration {
  position: absolute;
  bottom: 6px;
  right: 6px;
  background-color: rgba(0, 0, 0, 0.7);
  color: white;
  font-size: 12px;
  padding: 2px 6px;
  border-radius: 4px;
}

.info {
  padding: var(--spacing-sm);
}

.title {
  font-size: 14px;
  font-weight: 500;
  color: var(--text-primary);
  line-height: 1.4;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
  margin-bottom: var(--spacing-xs);
}

.video-card:hover .title {
  color: var(--bili-pink);
}

.meta {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: var(--spacing-sm);
  font-size: 12px;
  color: var(--text-tertiary);
}

.meta span {
  display: flex;
  align-items: center;
  gap: 4px;
}

.author {
  max-width: 100px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
