// 第3合集-AI时代编程新范式：Vibe Coding/260915-B站复刻与体感经验分享/one-shot/deepseek-v4.1-flash/run-03/web/src/components/video/VideoPlayer.vue
<template>
  <div
    ref="shellRef"
    class="player"
    :class="{ 'is-fullscreen': fullscreen, 'is-playing': playing }"
    @mousemove="showControls = true"
    @mouseleave="onLeave"
  >
    <video
      ref="videoRef"
      class="player__video"
      :src="src"
      :poster="poster"
      preload="metadata"
      playsinline
      @play="onPlay"
      @pause="onPause"
      @timeupdate="onTimeUpdate"
      @durationchange="onDurationChange"
      @waiting="buffering = true"
      @playing="buffering = false"
      @canplay="buffering = false"
      @error="onError"
      @click="togglePlay"
    />

    <!-- 弹幕层 -->
    <div v-show="danmakuOn" class="player__danmaku">
      <span
        v-for="item in liveDanmaku"
        :key="item.key"
        class="danmaku-item"
        :style="{ top: `${item.top}%`, color: item.color, animationDuration: `${item.duration}s` }"
      >
        {{ item.content }}
      </span>
    </div>

    <!-- 中央播放按钮 -->
    <button v-if="!playing" class="player__bigplay" @click="togglePlay">
      <SvgIcon name="play" :size="34" filled />
    </button>

    <div v-if="buffering && playing" class="player__loading">
      <span class="dot" /><span class="dot" /><span class="dot" />
    </div>

    <div v-if="errorMessage" class="player__error">
      <p>{{ errorMessage }}</p>
      <button class="btn-ghost" @click="retry">重新加载</button>
    </div>

    <!-- 控制栏 -->
    <div v-show="showControls || !playing" class="player__controls">
      <button class="ctrl" :title="playing ? '暂停' : '播放'" @click="togglePlay">
        <SvgIcon :name="playing ? 'pause' : 'play'" :size="20" :filled="!playing" />
      </button>

      <button class="ctrl" :title="muted ? '取消静音' : '静音'" @click="toggleMute">
        <SvgIcon :name="muted ? 'mute' : 'volume'" :size="20" />
      </button>

      <span class="player__time">{{ currentText }} / {{ durationText }}</span>

      <div
        class="player__progress"
        @click="seekByEvent"
        @mousedown="startDrag"
      >
        <div class="player__progress-bg">
          <div class="player__progress-loaded" :style="{ width: `${loadedPercent}%` }" />
          <div class="player__progress-played" :style="{ width: `${playedPercent}%` }">
            <i class="player__progress-dot" />
          </div>
        </div>
      </div>

      <button class="ctrl" :title="danmakuOn ? '关闭弹幕' : '开启弹幕'" @click="$emit('toggle-danmaku')">
        <SvgIcon name="danmaku" :size="20" :class="{ 'is-off': !danmakuOn }" />
      </button>

      <div class="player__quality">
        <button class="ctrl ctrl--text" @click="qualityOpen = !qualityOpen">
          {{ qualityLabel }}
          <SvgIcon name="arrowUp" :size="12" />
        </button>
        <transition name="pop">
          <ul v-show="qualityOpen" class="quality-menu">
            <li
              v-for="q in qualities"
              :key="q.qn"
              class="quality-menu__item"
              :class="{ 'is-active': q.qn === currentQuality }"
              @click="pickQuality(q.qn)"
            >
              {{ q.label }}
            </li>
          </ul>
        </transition>
      </div>

      <button class="ctrl" title="全屏" @click="toggleFullscreen">
        <SvgIcon name="fullscreen" :size="18" />
      </button>
    </div>

    <!-- 弹幕输入 -->
    <div v-show="showControls" class="player__danmaku-input">
      <input
        v-model="danmakuText"
        type="text"
        placeholder="发个弹幕见证当下"
        maxlength="60"
        @keydown.enter="sendDanmaku"
      />
      <button class="danmaku-send" @click="sendDanmaku">发送</button>
    </div>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import SvgIcon from '@/components/common/SvgIcon.vue';

/**
 * 播放器：真实 <video> + 后端流代理。
 * 弹幕为 B站 真实弹幕（按播放时间滚动出现），支持手动发弹幕。
 */
const props = defineProps({
  src: { type: String, default: '' },
  poster: { type: String, default: '' },
  danmakuList: { type: Array, default: () => [] },
  danmakuOn: { type: Boolean, default: true },
  qualities: { type: Array, default: () => [] },
  currentQuality: { type: Number, default: 64 },
  qualityLabel: { type: String, default: '720P' },
});

const emit = defineEmits(['progress', 'ended', 'toggle-danmaku', 'change-quality', 'send-danmaku']);

const shellRef = ref(null);
const videoRef = ref(null);
const playing = ref(false);
const muted = ref(false);
const buffering = ref(false);
const fullscreen = ref(false);
const showControls = ref(true);
const currentTime = ref(0);
const duration = ref(0);
const loaded = ref(0);
const errorMessage = ref('');
const qualityOpen = ref(false);
const danmakuText = ref('');
const liveDanmaku = ref([]);
let hideTimer = null;
let danmakuTimer = null;

const playedPercent = computed(() => (duration.value ? (currentTime.value / duration.value) * 100 : 0));
const loadedPercent = computed(() => (duration.value ? (loaded.value / duration.value) * 100 : 0));
const currentText = computed(() => fmt(currentTime.value));
const durationText = computed(() => fmt(duration.value));

function fmt(seconds) {
  const s = Math.max(0, Math.floor(seconds || 0));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  const pad = (n) => String(n).padStart(2, '0');
  return h > 0 ? `${pad(h)}:${pad(m)}:${pad(sec)}` : `${pad(m)}:${pad(sec)}`;
}

function togglePlay() {
  const el = videoRef.value;
  if (!el) return;
  if (!el.paused) {
    el.pause();
    return;
  }
  const attempt = el.play();
  if (attempt?.catch) {
    attempt.catch(() => {
      // 首帧还没就绪时 play() 会被中断，等 canplay 再自动重试一次
      const retry = () => {
        el.play().catch(() => {});
      };
      el.addEventListener('canplay', retry, { once: true });
    });
  }
}

function toggleMute() {
  const el = videoRef.value;
  if (!el) return;
  el.muted = !el.muted;
  muted.value = el.muted;
}

function onPlay() {
  playing.value = true;
  startDanmakuLoop();
}

function onPause() {
  playing.value = false;
}

function onTimeUpdate() {
  const el = videoRef.value;
  if (!el) return;
  currentTime.value = el.currentTime;
  emit('progress', el.currentTime);
  if (el.buffered.length) loaded.value = el.buffered.end(el.buffered.length - 1);
}

function onDurationChange() {
  duration.value = videoRef.value?.duration || 0;
}

function onError() {
  errorMessage.value = '视频加载失败，可能是网络或上游限制导致。';
  buffering.value = false;
}

function retry() {
  errorMessage.value = '';
  videoRef.value?.load();
}

function onLeave() {
  if (playing.value) showControls.value = false;
}

function seekByEvent(event) {
  const bar = event.currentTarget.getBoundingClientRect();
  const ratio = Math.min(1, Math.max(0, (event.clientX - bar.left) / bar.width));
  if (videoRef.value && duration.value) {
    videoRef.value.currentTime = ratio * duration.value;
  }
}

function startDrag() {
  const onMove = (e) => {
    const bar = shellRef.value?.querySelector('.player__progress');
    if (!bar || !duration.value) return;
    const rect = bar.getBoundingClientRect();
    const ratio = Math.min(1, Math.max(0, (e.clientX - rect.left) / rect.width));
    videoRef.value.currentTime = ratio * duration.value;
  };
  const onUp = () => {
    window.removeEventListener('mousemove', onMove);
    window.removeEventListener('mouseup', onUp);
  };
  window.addEventListener('mousemove', onMove);
  window.addEventListener('mouseup', onUp);
}

function toggleFullscreen() {
  const el = shellRef.value;
  if (!document.fullscreenElement) {
    el?.requestFullscreen?.();
  } else {
    document.exitFullscreen?.();
  }
}

function onFullscreenChange() {
  fullscreen.value = Boolean(document.fullscreenElement);
}

function pickQuality(qn) {
  qualityOpen.value = false;
  emit('change-quality', qn);
}

function sendDanmaku() {
  const content = danmakuText.value.trim();
  if (!content) return;
  emit('send-danmaku', { content, timeMs: Math.round(currentTime.value * 1000) });
  pushDanmaku({ content, color: '#FFFFFF' });
  danmakuText.value = '';
}

/** 把弹幕推到屏幕上（真实播放时间轴） */
function pushDanmaku(item) {
  liveDanmaku.value = [
    ...liveDanmaku.value.slice(-24),
    {
      ...item,
      key: `${item.content}-${Date.now()}-${Math.random()}`,
      top: 4 + Math.random() * 66,
      duration: 7 + Math.random() * 3,
    },
  ];
}

function startDanmakuLoop() {
  if (danmakuTimer) return;
  danmakuTimer = setInterval(() => {
    if (!props.danmakuOn || !playing.value) return;
    const el = videoRef.value;
    if (!el) return;
    const t = el.currentTime * 1000;
    // 命中当前时间窗口的弹幕，最多同时推 2 条
    const hits = props.danmakuList.filter(
      (d) => d.timeMs >= t - 400 && d.timeMs < t + 400,
    );
    hits.slice(0, 2).forEach((d) => pushDanmaku(d));
    // 清理已滚出屏幕的弹幕
    if (liveDanmaku.value.length > 34) {
      liveDanmaku.value = liveDanmaku.value.slice(-26);
    }
  }, 900);
}

function scheduleHide() {
  clearTimeout(hideTimer);
  hideTimer = setTimeout(() => {
    if (playing.value) showControls.value = false;
  }, 2600);
}

watch(
  () => props.src,
  () => {
    errorMessage.value = '';
    playing.value = false;
    currentTime.value = 0;
    duration.value = 0;
    liveDanmaku.value = [];
  },
);

watch(showControls, (val) => {
  if (val) scheduleHide();
});

window.addEventListener('fullscreenchange', onFullscreenChange);

onBeforeUnmount(() => {
  clearInterval(danmakuTimer);
  clearTimeout(hideTimer);
  window.removeEventListener('fullscreenchange', onFullscreenChange);
});

defineExpose({
  play: () => videoRef.value?.play(),
  pause: () => videoRef.value?.pause(),
  get element() {
    return videoRef.value;
  },
});
</script>

<style lang="scss" scoped>
@use '@/styles/variables.scss' as *;

.player {
  position: relative;
  width: 100%;
  aspect-ratio: 16 / 9;
  background: #000;
  border-radius: $radius-lg;
  overflow: hidden;
  user-select: none;

  &.is-fullscreen {
    border-radius: 0;
    aspect-ratio: auto;
    height: 100vh;
  }

  &__video {
    width: 100%;
    height: 100%;
    display: block;
    background: #000;
  }

  &__danmaku {
    position: absolute;
    inset: 0 0 64px 0;
    overflow: hidden;
    pointer-events: none;
  }

  &__bigplay {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 72px;
    height: 72px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #fff;
    background: rgba(0, 0, 0, 0.42);
    border: 2px solid rgba(255, 255, 255, 0.75);
    border-radius: 50%;
    padding-left: 5px;
    transition: all $transition-fast;

    &:hover {
      background: $brand-pink;
      border-color: #fff;
      transform: translate(-50%, -50%) scale(1.06);
    }
  }

  &__loading {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    display: flex;
    gap: 6px;

    .dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: $brand-pink;
      animation: bounce 1s infinite ease-in-out;

      &:nth-child(2) {
        animation-delay: 0.15s;
      }

      &:nth-child(3) {
        animation-delay: 0.3s;
      }
    }
  }

  &__error {
    position: absolute;
    inset: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 12px;
    color: #fff;
    background: rgba(0, 0, 0, 0.72);
    font-size: 14px;
  }

  &__controls {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    height: 56px;
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 0 12px;
    background: linear-gradient(180deg, transparent, rgba(0, 0, 0, 0.78));
    z-index: 3;
  }

  &__time {
    font-size: 12px;
    color: #fff;
    font-variant-numeric: tabular-nums;
    margin: 0 4px;
  }

  &__progress {
    flex: 1;
    height: 16px;
    display: flex;
    align-items: center;
    cursor: pointer;
  }

  &__progress-bg {
    position: relative;
    width: 100%;
    height: 4px;
    border-radius: 2px;
    background: rgba(255, 255, 255, 0.3);
  }

  &__progress-loaded {
    position: absolute;
    left: 0;
    top: 0;
    height: 100%;
    background: rgba(255, 255, 255, 0.45);
    border-radius: 2px;
  }

  &__progress-played {
    position: absolute;
    left: 0;
    top: 0;
    height: 100%;
    background: $brand-pink;
    border-radius: 2px;
    display: flex;
    align-items: center;
    justify-content: flex-end;
  }

  &__progress-dot {
    width: 12px;
    height: 12px;
    margin-right: -6px;
    border-radius: 50%;
    background: #fff;
    box-shadow: 0 0 4px rgba(0, 0, 0, 0.4);
    opacity: 0;
    transition: opacity $transition-fast;
  }

  &:hover &__progress-dot {
    opacity: 1;
  }

  &__quality {
    position: relative;
  }

  &__danmaku-input {
    position: absolute;
    right: 12px;
    bottom: 64px;
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 5px 6px 5px 12px;
    background: rgba(0, 0, 0, 0.55);
    border-radius: 20px;
    z-index: 3;

    input {
      width: 190px;
      font-size: 13px;
      color: #fff;

      &::placeholder {
        color: rgba(255, 255, 255, 0.6);
      }
    }
  }
}

.ctrl {
  width: 34px;
  height: 34px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  border-radius: $radius-md;
  transition: all $transition-fast;

  &:hover {
    background: rgba(255, 255, 255, 0.16);
    color: $brand-pink;
  }

  &--text {
    width: auto;
    padding: 0 8px;
    gap: 2px;
    font-size: 12px;
  }

  :deep(.is-off) {
    opacity: 0.45;
  }
}

.danmaku-send {
  height: 24px;
  padding: 0 12px;
  font-size: 12px;
  color: #fff;
  background: $brand-pink;
  border-radius: 14px;

  &:hover {
    background: $brand-pink-hover;
  }
}

.quality-menu {
  position: absolute;
  right: 0;
  bottom: 40px;
  width: 108px;
  padding: 4px;
  background: rgba(20, 20, 20, 0.92);
  border-radius: $radius-md;
  z-index: 5;

  &__item {
    padding: 7px 10px;
    font-size: 13px;
    color: rgba(255, 255, 255, 0.8);
    border-radius: $radius-sm;
    cursor: pointer;

    &:hover {
      background: rgba(255, 255, 255, 0.12);
    }

    &.is-active {
      color: $brand-pink;
      font-weight: 600;
    }
  }
}

.danmaku-item {
  position: absolute;
  left: 100%;
  white-space: nowrap;
  font-size: 16px;
  font-weight: 500;
  text-shadow: 0 1px 3px rgba(0, 0, 0, 0.9);
  animation-name: danmaku-move;
  animation-timing-function: linear;
  animation-fill-mode: forwards;
  will-change: transform;
}

@keyframes danmaku-move {
  from {
    transform: translateX(0);
  }
  to {
    transform: translateX(calc(-100vw - 100%));
  }
}

@keyframes bounce {
  0%,
  80%,
  100% {
    transform: scale(0.6);
    opacity: 0.5;
  }
  40% {
    transform: scale(1);
    opacity: 1;
  }
}
</style>

// 第3合集-AI时代编程新范式：Vibe Coding/260915-B站复刻与体感经验分享/one-shot/claude-opus-5/run-01/web/src/components/video/VideoPlayer.tsx
/**
 * 播放器：真实 <video> 播放 + 自研控制条 + 弹幕层。
 * 支持：播放/暂停、进度拖拽、音量、倍速、弹幕开关、宽屏、全屏、发送弹幕。
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import { Icon } from '../common/Icon';
import { useDanmakuEngine } from '../../hooks/useDanmakuEngine';
import { formatDuration } from '../../utils/format';
import type { DanmakuItem } from '../../types';
import './player.css';

interface Props {
  src: string;
  poster: string;
  danmaku: DanmakuItem[];
  wide: boolean;
  onToggleWide: () => void;
  onSendDanmaku: (text: string, progress: number) => Promise<DanmakuItem | null>;
}

const SPEEDS = [2, 1.5, 1.25, 1, 0.75, 0.5];

export function VideoPlayer({ src, poster, danmaku, wide, onToggleWide, onSendDanmaku }: Props) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const shellRef = useRef<HTMLDivElement>(null);
  const progressRef = useRef<HTMLDivElement>(null);
  const hideTimer = useRef<number | undefined>(undefined);

  const [playing, setPlaying] = useState(false);
  const [current, setCurrent] = useState(0);
  const [duration, setDuration] = useState(0);
  const [buffered, setBuffered] = useState(0);
  const [muted, setMuted] = useState(true);
  const [volume, setVolume] = useState(0.7);
  const [speed, setSpeed] = useState(1);
  const [danmakuOn, setDanmakuOn] = useState(true);
  const [controlsVisible, setControlsVisible] = useState(true);
  const [fullscreen, setFullscreen] = useState(false);
  const [draft, setDraft] = useState('');
  const [danmakuColor, setDanmakuColor] = useState('#ffffff');

  const { active, remove, emit } = useDanmakuEngine(videoRef, danmaku, danmakuOn);

  /* ----------------------------- 播放控制 ----------------------------- */

  const togglePlay = useCallback(() => {
    const video = videoRef.current;
    if (!video) return;
    if (video.paused) video.play().catch(() => undefined);
    else video.pause();
  }, []);

  // 换稿件时自动从头播放（静音自动播放，浏览器策略允许）
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    video.currentTime = 0;
    video.play().catch(() => setPlaying(false));
  }, [src]);

  useEffect(() => {
    const video = videoRef.current;
    if (video) video.playbackRate = speed;
  }, [speed]);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    video.volume = volume;
    video.muted = muted;
  }, [volume, muted]);

  useEffect(() => {
    const onFsChange = () => setFullscreen(Boolean(document.fullscreenElement));
    document.addEventListener('fullscreenchange', onFsChange);
    return () => document.removeEventListener('fullscreenchange', onFsChange);
  }, []);

  // 空格播放/暂停、左右方向键快进快退
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement;
      if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA') return;
      const video = videoRef.current;
      if (!video) return;
      if (event.code === 'Space') {
        event.preventDefault();
        togglePlay();
      }
      if (event.code === 'ArrowRight') video.currentTime = Math.min(video.duration, video.currentTime + 5);
      if (event.code === 'ArrowLeft') video.currentTime = Math.max(0, video.currentTime - 5);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [togglePlay]);

  const showControls = () => {
    setControlsVisible(true);
    window.clearTimeout(hideTimer.current);
    hideTimer.current = window.setTimeout(() => setControlsVisible(false), 2600);
  };

  /* ----------------------------- 进度控制 ----------------------------- */

  const seekTo = (clientX: number) => {
    const bar = progressRef.current;
    const video = videoRef.current;
    if (!bar || !video || !video.duration) return;
    const rect = bar.getBoundingClientRect();
    const ratio = Math.min(1, Math.max(0, (clientX - rect.left) / rect.width));
    video.currentTime = ratio * video.duration;
    setCurrent(video.currentTime);
  };

  const onProgressDown = (event: React.MouseEvent) => {
    seekTo(event.clientX);
    const onMove = (e: MouseEvent) => seekTo(e.clientX);
    const onUp = () => {
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
    };
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
  };

  /* ----------------------------- 发送弹幕 ----------------------------- */

  const send = async () => {
    const text = draft.trim();
    const video = videoRef.current;
    if (!text || !video) return;
    const progress = video.duration ? video.currentTime / video.duration : 0;
    setDraft('');
    const item = await onSendDanmaku(text, progress);
    emit(
      item ?? {
        id: `local-${Date.now()}`,
        p: progress,
        time: Math.floor(video.currentTime),
        text,
        color: danmakuColor,
        mode: 'scroll',
        fontSize: 25,
        self: true,
      },
    );
  };

  const progressPercent = duration ? (current / duration) * 100 : 0;

  return (
    <div
      className={`player ${controlsVisible || !playing ? 'show-controls' : ''} ${
        fullscreen ? 'is-fullscreen' : ''
      }`}
      ref={shellRef}
      onMouseMove={showControls}
      onMouseLeave={() => playing && setControlsVisible(false)}
    >
      <div className="player__stage" onClick={togglePlay} onDoubleClick={() => toggleFullscreen(shellRef, fullscreen)}>
        <video
          ref={videoRef}
          className="player__video"
          src={src}
          poster={poster}
          loop
          playsInline
          muted={muted}
          preload="auto"
          onPlay={() => {
            setPlaying(true);
            showControls();
          }}
          onPause={() => setPlaying(false)}
          onTimeUpdate={(e) => setCurrent(e.currentTarget.currentTime)}
          onLoadedMetadata={(e) => setDuration(e.currentTarget.duration)}
          onProgress={(e) => {
            const v = e.currentTarget;
            if (v.buffered.length) setBuffered(v.buffered.end(v.buffered.length - 1));
          }}
        />

        {/* 弹幕层 */}
        <div className={`player__danmaku ${danmakuOn ? '' : 'is-off'}`}>
          {active.map((item) => (
            <span
              key={item.key}
              className={`danmaku danmaku--${item.mode} ${item.self ? 'is-self' : ''}`}
              style={{
                top: `${item.lane * 9 + 2}%`,
                color: item.color,
                fontSize: item.fontSize > 25 ? 23 : 19,
                animationPlayState: playing ? 'running' : 'paused',
              }}
              onAnimationEnd={() => remove(item.key)}
            >
              {item.text}
            </span>
          ))}
        </div>

        {!playing && (
          <button className="player__big-play" onClick={togglePlay} title="播放">
            <Icon name="play" size={30} />
          </button>
        )}

        {muted && (
          <button
            className="player__unmute"
            onClick={(e) => {
              e.stopPropagation();
              setMuted(false);
            }}
          >
            <Icon name="mute" size={14} /> 已静音播放，点击开启声音
          </button>
        )}
      </div>

      <div className="player__controls" onClick={(e) => e.stopPropagation()}>
        <div className="player__progress" ref={progressRef} onMouseDown={onProgressDown}>
          <div className="player__progress-bg" />
          <div
            className="player__progress-buffer"
            style={{ width: duration ? `${(buffered / duration) * 100}%` : '0%' }}
          />
          <div className="player__progress-played" style={{ width: `${progressPercent}%` }}>
            <span className="player__progress-thumb" />
          </div>
        </div>

        <div className="player__bar">
          <button className="player__btn" onClick={togglePlay} title={playing ? '暂停' : '播放'}>
            <Icon name={playing ? 'pause' : 'play'} size={20} />
          </button>
          <span className="player__time">
            {formatDuration(current)} / {formatDuration(duration)}
          </span>

          <div className="player__danmaku-input">
            <button
              className="player__color"
              style={{ background: danmakuColor }}
              title="弹幕颜色"
              onClick={() =>
                setDanmakuColor((prev) => {
                  const colors = ['#ffffff', '#ff7f24', '#66ccff', '#7ac943', '#ffd700'];
                  return colors[(colors.indexOf(prev) + 1) % colors.length];
                })
              }
            />
            <input
              value={draft}
              placeholder="发个友善的弹幕见证当下"
              maxLength={40}
              onChange={(e) => setDraft(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') void send();
              }}
            />
            <button className="player__send" onClick={() => void send()}>
              发送
            </button>
          </div>

          <div className="player__right">
            <button
              className={`player__btn ${danmakuOn ? '' : 'is-off'}`}
              title={danmakuOn ? '关闭弹幕' : '开启弹幕'}
              onClick={() => setDanmakuOn((v) => !v)}
            >
              <Icon name="danmaku" size={20} />
            </button>

            <div className="player__pop player__pop--volume">
              <button
                className="player__btn"
                title="音量"
                onClick={() => setMuted((v) => !v)}
              >
                <Icon name={muted || volume === 0 ? 'mute' : 'volume'} size={20} />
              </button>
              <div className="player__pop-body">
                <input
                  type="range"
                  min={0}
                  max={1}
                  step={0.05}
                  value={muted ? 0 : volume}
                  onChange={(e) => {
                    setVolume(Number(e.target.value));
                    setMuted(Number(e.target.value) === 0);
                  }}
                />
              </div>
            </div>

            <div className="player__pop player__pop--speed">
              <button className="player__btn player__btn--text" title="倍速">
                {speed === 1 ? '倍速' : `${speed}x`}
              </button>
              <div className="player__pop-body">
                {SPEEDS.map((value) => (
                  <button
                    key={value}
                    className={speed === value ? 'is-active' : ''}
                    onClick={() => setSpeed(value)}
                  >
                    {value === 1 ? '1.0x' : `${value}x`}
                  </button>
                ))}
              </div>
            </div>

            <button
              className={`player__btn ${wide ? 'is-active' : ''}`}
              title="宽屏"
              onClick={onToggleWide}
            >
              <Icon name="wide" size={20} />
            </button>
            <button
              className="player__btn"
              title="全屏"
              onClick={() => toggleFullscreen(shellRef, fullscreen)}
            >
              <Icon name="fullscreen" size={20} />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function toggleFullscreen(ref: React.RefObject<HTMLElement>, isFullscreen: boolean) {
  if (isFullscreen) void document.exitFullscreen();
  else void ref.current?.requestFullscreen().catch(() => undefined);
}
